# Generated by Django 3.1.3 on 2020-12-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='article_isi',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_heading',
            new_name='article_judul',
        ),
    ]
